<a href="https://colab.research.google.com/github/fstoco/machine-learning/blob/main/SVM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example:
Apply SVM on iris dataset for classification analysis where Species is the target variable.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [ ]:
import pandas as pd
dataset= pd.read_csv('Iris.csv')
dataset.head(6)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa

In [ ]:
X=dataset.drop('Species',axis=1)
y=dataset['Species']
from sklearn.model_selection import train_test_split 



In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=3) # testset is 30%
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.svm import SVC

svc = SVC(kernel='linear')
svc.fit(X_train, y_train)
ypred = svc.predict(X_test) # the vector of predictions 
acc= accuracy_score(y_test, ypred)
confusion_matrix(y_test, ypred)
 
#df=pd.DataFrame({'Actual':y_test, 'Predicted':ypred})
 




array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 14]])

In [ ]:
acc

0.9777777777777777

#create a for loop to assess all kernels on the same train and testset




In [ ]:
acc_vect=[]
ker=['linear', 'poly', 'rbf', 'sigmoid']
for i in ker:
  svc = SVC(kernel=i) #specify the kernel
  svc.fit(X_train, y_train)
  ypred = svc.predict(X_test)
  acc= accuracy_score(y_test, ypred)
  acc_vect.append(acc)

print('accuracy for linear, poly, rbf, sigmoid:',acc_vect)

accuracy for linear, poly, rbf, sigmoid: [0.9777777777777777, 0.9777777777777777, 0.9555555555555556, 0.24444444444444444]


Evaluate the performance of SVM for different kernel where the same datasets are used. 



In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) # testset is 30%
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.svm import SVC

acc_vect=[]
ker=['linear', 'poly', 'rbf', 'sigmoid']
for i in ker:
  svc = SVC(kernel=i) #specify the kernel
  svc.fit(X_train, y_train)
  ypred = svc.predict(X_test)
  acc= accuracy_score(y_test, ypred)
  acc_vect.append(acc)

print('accuracy for linear, poly, rbf, sigmoid:',acc_vect)



accuracy for linear, poly, rbf, sigmoid: [0.9555555555555556, 0.9555555555555556, 0.9555555555555556, 0.26666666666666666]


Evaluate the result of performance for different kernels of svc in 1000 MC runs

In [ ]:
import statistics as st
acc_vect=[]
ker=['linear', 'poly', 'rbf', 'sigmoid']
for i in ker:
  acc_mc=[]
  for j in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=j) # testset is 30%
    svc = SVC(kernel=i) #specify the kernel
    svc.fit(X_train, y_train)
    ypred = svc.predict(X_test)
    acc= accuracy_score(y_test, ypred)
    acc_mc.append(acc)
  acc_vect.append(st.mean(acc_mc))

print('accuracy for linear, poly, rbf, sigmoid:',acc_vect)


accuracy for linear, poly, rbf, sigmoid: [0.975, 0.9654444444444444, 0.9586666666666667, 0.2528666666666667]


# Example 1:(classification)
Apply SVM on red-wine dataset, to model quality as the output variable in order to accomplish the classification task. 
a)Evaluate the results for different kernels in 10 MC runs. which kernel does outperform? 
b) redo the classification using NB and Multinomial logistic regression, and compare the result versus the best kernel of SVM.



#Example 2:(regression)
Apply regression task to model pH (output) on other variables in the dataset using SVM and multiple linear regression in 10 mc runs. 

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red.csv


In [ ]:
import pandas as pd
dataset= pd.read_csv('winequality-red.csv')
dataset.head(6)

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5

[6 rows x 12 columns]

In [ ]:
dataset.info()

In [ ]:
X=dataset.drop('quality',axis=1)
y=dataset['quality']
from sklearn.model_selection import train_test_split 
  

In [ ]:
#from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
from sklearn.svm import SVC

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) # testset is 30%
svc = SVC(kernel='linear') #specify the kernel
svc.fit(X_train, y_train)
ypred = svc.predict(X_test)
re= classification_report(y_test, ypred)
cm=confusion_matrix(y_test, ypred)
print(cm)

print(re)

[[  0   0   2   1   0   0]
 [  0   0   7   4   0   0]
 [  0   0 155  41   0   0]
 [  0   0  83 120   0   0]
 [  0   0   7  54   0   0]
 [  0   0   0   6   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00        11
           5       0.61      0.79      0.69       196
           6       0.53      0.59      0.56       203
           7       0.00      0.00      0.00        61
           8       0.00      0.00      0.00         6

    accuracy                           0.57       480
   macro avg       0.19      0.23      0.21       480
weighted avg       0.47      0.57      0.52       480



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import statistics as st
acc_vect=[]
ker=['linear', 'poly', 'rbf', 'sigmoid']
for i in ker:
  acc_mc=[]
  for j in range(10):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) # testset is 30%
    svc = SVC(kernel=i) #specify the kernel
    svc.fit(X_train, y_train)
    ypred = svc.predict(X_test)
    acc= accuracy_score(y_test, ypred)
    acc_mc.append(acc)
  acc_vect.append(st.mean(acc_mc))

print('accuracy for linear, poly, rbf, sigmoid:',acc_vect)

accuracy for linear, poly, rbf, sigmoid: [0.5833333333333334, 0.480625, 0.49333333333333335, 0.40958333333333335]


Based on 10 mc runs, the best kernel is linear. Therefore, we need to compare the performance of linear kernel with NB and MLR. 




In [ ]:
import warnings
warnings.filterwarnings("ignore")
acc_vect=[]
 
acc_mc_1=[]
acc_mc_2=[]
acc_mc_3=[]
for j in range(10):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) # testset is 30%
  svc = SVC(kernel='linear') #specify the kernel
  svc.fit(X_train, y_train)
  ypred = svc.predict(X_test)
  acc_svl= accuracy_score(y_test, ypred)
  # NB
  from sklearn.naive_bayes import GaussianNB
  gnb=GaussianNB()
  gnb.fit(X_train,y_train)
  y_pred_gnb=gnb.predict(X_test)
  acc_nb=accuracy_score(y_test,y_pred_gnb) 
  #MLR
  from sklearn.linear_model import LogisticRegression
  LR =LogisticRegression(random_state=0) # describe the model
  model=LR.fit(X_train, y_train) #fit the model using trainset
  pred_LR=LR.predict(X_test) # predict the output variable using testset
  acc_MLR=accuracy_score(y_test, pred_LR) # compute accuracy
  acc_mc_1.append(acc_svl)
  acc_mc_2.append(acc_nb)
  acc_mc_3.append(acc_MLR)
   



In [ ]:
import statistics as st
print('accuracy for svm with linear, NB, MLR:',st.mean(acc_mc_1), st.mean(acc_mc_2),st.mean(acc_mc_3))

accuracy for svm with linear, NB, MLR: 0.589375 0.538125 0.5825


In [ ]:
dataset.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
inputs=['fixed acidity','volatile acidity','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','sulphates','alcohol','quality']

Apply regression task to model pH on other variables in the dataset using SVM and multiple linear regression in 10 mc runs. 







In [ ]:
import pandas as pd
import seaborn as sns
  
from sklearn.metrics import mean_absolute_error, mean_squared_error  # regression metrics
 
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression  # multiple linear regression
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
 X=dataset.drop('pH',axis=1)
y=dataset['pH']
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) # testset is 30%

In [ ]:
svr_rbf = SVR(kernel='rbf')
svr_lineal = SVR(kernel='linear')
lr = LinearRegression()

In [ ]:
inputs=['fixed acidity','volatile acidity','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','sulphates','alcohol','quality']

In [ ]:
def launch_model(name,model, X_train, y_train, X_test, y_test):
    start = time.time()
    model.fit(X_train[inputs], y_train)
    y_pred = model.predict(X_test[inputs])
    print ('MSE test', mean_squared_error(y_test, y_pred))
     


In [ ]:
results = []
print ('-----------')
print ('SVR - RBF')
print ('-----------')
results.append(launch_model('SVR - RBF', svr_rbf, X_train, y_train, X_test, y_test))
print ('-----------')
print ('SVR - linear')
print ('-----------')
results.append(launch_model('SVR - linear', svr_lineal, X_train, y_train, X_test, y_test))
print ('-----------')
print ('Linear Regresion ')
print ('-----------')
results.append(launch_model(' linear Reg ', lr, X_train, y_train, X_test, y_test))

-----------
SVR - RBF
-----------
MSE test 0.010891889440701704
-----------
SVR - linear
-----------
MSE test 0.010334591332512489
-----------
Linear Regresion 
-----------
MSE test 0.007174340073339227


#Example: Consider boston_house_prices dataset  Apply regression task to model medv (output) on other variables in the dataset using SVM and multiple linear regression in 100 mc runs. Specify the best Regression model`.

# design the recommendation system to predict MEDV for the first sample in the dataset. 



In [ ]:
# find the best model

In [ ]:
# design the recommendation system

x1=input('CRIM:')  #SepalLengthCm	SepalWidthCm	PetalLengthCm	PetalWidthCm
x2=input('ZN:')
x3=input('INDUS:')
x4=input(':')
x=np.array([x1,x2,x3,x4])
y=svr_linear.predict(x.reshape(1,-1))
print('type of folower:',y)

In [ ]:
recom=svr_linear.predict(dataset.iloc[1:2,1:15])